# Muhammad and his successors

Hoyland, Robert. "Writing the Biography of the Prophet Muhammad: Problems and Solutions", *History Compass 5* (2007): 581-602.\
Kennedy, Hugh. *The Prophet and the Age of the Caliphates,* 29-81.\

**Primary sources:** 1) Ḥadīth (selections of \*aḥādīth\* about theProphet); 2) Maʿmar b. Rāshid. _Kitāb al-maghāzī,_ edited and translated by Sean W. Anthony as *The Expeditions: An Early Biography of Muhammad.* New York and London, 2014, 193-215.

**Further reading:**
Anthony, Sean. *Muhammad and the Empires of Faith.* Oakland, 2020, 1-82.\
Crone, Patricia. *Slaves on Horses,* 18-26.\
Hoyland, Robert. "Writing the Biography of the Prophet Muhammad: Problems and Solutions", *History Compass 5* (2007): 581-602.Kennedy, Hugh. *The Prophet and the Age of the Caliphates,* 29-81.


Comments from Sarah and Mohammad added and substantially revised in August 2022
Working on it in June 2023


Chapter 7. A Community of Jurists

Aslisho Qurboniev


When we saw historical traces being obliterated and history being wiped out, our thoughts were provoked to compose the history of the shaykhs who passed before us, the members of this daʿwa and the righteous amongst them, and to mention their good deeds, the uprightness of their character, the magnificence of their ways, and the extent of their virtues. To this end, we wrote down whatever we could, fearing that people may disregard it and consign it to oblivion. We plead with God and ask Him for protection and for His reward for our undertaking, for He is our benefactor. He is sufficient for us, and He is the best protector! 

Abū Zakariyāʾ al-Warjalānī (d. after 470/1078)


At the turn of the ninth century, two learned men entered Ifrīqiya (a province roughly corresponding to modern Tunisia) each carrying a compendium of Islamic law with him. One of them, Asad b. al-Furāt (d. 213/828), had grown up in Qayrawān and was now returning there after a three-year journey in pursuit of knowledge in Ḥijāz, ʿIrāq and Egypt.  His book was a compilation of legal opinions transmitted from Mālik b. Anas by his Egyptian student ʿAbd al-Raḥmān Ibn al-Qāsim al-ʿUtaqī (d. 191/807), with whom Asad had studied in Egypt. He had also studied directly with Mālik b. Anas in Medina and with several students of Abū Ḥanīfa in ʿIrāq, thus connecting himself to the two most prominent jurists of the time. Asad b. al-Furāt’s compilation, known as Asadiyya, reportedly consisted of questions that originated in the Iraqi milieu for which Asad had sought Mālik’s answers. The compilation was not flawless and was criticised. Nevertheless, it gained him admiration among the legal scholars of Qayrawān until it was superseded by an updated version brought to Qayrawān around AD 804, by a local scholar, Saḥnūn b. Saʿīd, who allegedly went to the East to remedy the problems of the Asadiyya.  This story lays bare the nature of the competition between these two Ifrīqiyan jurists. According to the Mālikī sources, Saḥnūn obtained a full copy of the Asadiyya without Asad’s approval and took it to Egypt, where he read it with Ibn al-Qāsim and produced a revised version. To stop Asad from teaching his version, the story goes, Ibn al-Qāsim sent him an upsetting letter, but according to the Mālikī tradition, he accepted the authoritativeness of Saḥnūn’s rival compilation, now called the Mudawwana.  The Mudawwana subsequently became the most authoritative legal compendium for the Mālikī community of the Islamic West, and through its transmission by Saḥnūn’s students, it came to represent the crowning achievement of their teacher and their scholarly community whereas Asad  was remembered mainly as the conqueror of Sicily for the Aghlabids.
The second book was brought to Ifrīqiya by Abū Ghānim Bishr b. Ghānim al-Khurāsānī (d. early third/ninth century). It was also called Mudawwana, but it had nothing to do with the Mālikīs.  This book belonged to the Ibāḍī community, and it is considered ‘the oldest Ibāḍī treatise on general jurisprudence’, based on the teachings of the Basran Ibāḍī scholar Abū ʿUbayda Muslim al-Tamīmī (d. circa 136–58/754–75).  Abū ʿUbayda was recognised as an Ibāḍī imam and is known for organising and dispatching Ibāḍī missionaries, called ḥamalat al-ʿilm (bearers of knowledge).  One of the first missionaries sent by Abū ʿUbayda, Abū al-Khaṭṭāb al-Maʿāfirī, managed to capture Tripoli and, briefly, even Qayrawān, where he appointed ʿAbd al-Raḥmān b. Rustam the future founder of the Rustamid state of Tahert (r. 161–71/778–88), as the governor.  Abū Ghānim, who belonged to another generation of the ḥamalat al-ʿilm, was travelling to Tahert to visit the second Rustamid imam, ʿAbd al-Wahhāb b. ʿAbd al-Raḥmān (r. 171–208/788–824). The Ibāḍī tradition preserves an interesting memory of Abū Ghānim’s passing by Jabal Nafūsa, the Ibāḍī stronghold in Ifrīqiya, which highlights the importance of his Mudawwana for the survival of the community:
When Abū Ghānim Bishr b. Ghānim al-Khurāsānī travelled from the Mashriq to the Maghrib for an audience with the [Rustamid] imam ʿAbd al-Wahhāb [168–208/784–823] – may God be pleased with him – he brought his famous Mudawwana with him. He transmitted it from the students of Abū ʿUbayda – may God be pleased with him – and had fixed the transmission in writing. On the way to Tahert, [Abū Ghānim] passed through Jabal Nafūsa, where he lent the abovementioned book to the young ʿAmrūs but declined [the latter’s] request to copy it. So ʿAmrūs contemplated copying the book [without permission] and eventually gave in to his desire for knowledge, so he devoted himself to the task of copying the book while his sister dictated to him.  He would [copy] the book until the sun reached him. Then he would move to sit in the shade for copying, with the original copy still in his sister’s hands but his eyes fixated on the writing because of his extreme passion for the revival of knowledge (ʿilm). By the time Abū Ghānim returned from Tahert, ʿAmrūs had completed the copying. Then he put [the book] back where it had been. When the owner retrieved the [original] book, he saw an ink dot on a part of it and asked him: ‘Did you steal this?’ He [ʿAmrūs] replied: ‘Yes; call me a knowledge thief, by transmitting not by stealing? (akhbāran lā amran).’ This book consisted of twelve parts. Afterwards, the treasury of Tahert was burnt and plundered [by the Fāṭimids]. Were it not for ʿAmrūs’s holding on to this book, the community (ahl al-madhhab) in the lands of the Maghrib would have had no collection (dīwān) to rely on. This was made possible [only] through ʿAmrūs’s good will, blessing and good fortune. 
The foundational stories of Asad b. al-Furāt and Abū Ghānim reveal the importance of the written word as the cornerstone of communal memory and identity both for the urban Arabic-speaking Mālikīs and the Berber-speaking Ibāḍīs of rural Ifrīqiya. The rise of the Shīʿī Fāṭimids in the tenth century put an end to the Ibāḍī state of Tahert and led to the suppression of several major Ibāḍī uprisings in the mountains. The Mālikī scholars of Qayrawān, although largely left to their own devices, also saw the Fāṭimid rule as a threat to their community. Deprived of state patronage, both communities had to rely on strategies of their own to maintain their communal identities and boundaries.  Thus, they often saw their memory practices, as expressed in the quotation from Abū Zakariyyā al-Warjalānī that opens this chapter, as a struggle against oblivion.
In this chapter I explore the mechanisms, instruments and above all incentives that maintained these communities. I ask: what sustained the sociocultural and ideological continuity that was vital to their survival as distinct communities? Answering this question will hopefully provide fresh insights into the cultural memory of Muslims and of the numerous subgroups that produced the textual heritage of Islam. In particular, the chapter will illustrate the interdependence of texts, narratives and memory in the formation of the most important community of religious scholars in the Islamic West, the Mālikīs. 
Scholarly communities, especially the early Mālikīs of the Islamic West, have been studied on the bases of their textual output, but memory processes have rarely been considered in the formation of the tradition. This perspective helps bring out the social function of memory practices and the contexts that made these practices significant to the Mālikī community. Evidence of text reuse adds further insight into the process through which the cultural memory of the Islamic West was formed and in which the Mālikī jurists played a prominent role. Reuse data shows how texts (both legal texts and biographies) were accumulated over time into massive compilations, and in the case of legal texts were later condensed into shorter but much more practical abridgements (mukhtaṣar, ikhtiṣār, etc.), which again invited participation through commentary and elaboration from the scholarly community (Figures 1 and 4).

The Mālikī Community of Qayrawān and Their Remembrance of the Past

In the medieval Islamic world, religion and ethnic affiliations were both strong markers of community, while ethnic or tribal belongings often intersected with religious proclivities.  The rural medieval Maghrib with its predominantly Berber population provides an interesting case of the interplay between tribal and religious affiliations,  which contrasted with the urban centres occupied predominantly by Arabs and other Arabised Muslims. For the latter, at least for the educated elite, the biographical collections inform us, religious belonging increasingly played a more prominent role as a marker of community than did tribal and regional ties. To put it differently, ethnic origin was not a barrier to membership in a community defined by its doctrinal position, such as the Mālikī community. On the other hand, identification with geographies and space also often intersected with a school of interpretation, for which the Medinian and Kūfans/ʿIrāqīs of Qayrawān are our most fitting examples. These two groups initially associated with the region where their major authorities resided later became known as Mālikī and Ḥanafī respectively? Thus, for the cosmopolitan and literate societies of the Islamic world, a new type of belonging to a community defined by its legal and doctrinal positions and sometimes by mutually exclusive interpretations of religion, became more important.  The madhhab, even in the loosest sense of the word, became the main form of affiliation, networking and knowledge transmission, and subsequently a  framework  for imagining the community and its continuity and coherence in the past. As I will argue below, texts and textual networks constituted crucial instruments for the legitimation, preservation and promotion of these scholarly communities through the shaping and reshaping of their pasts. 
The case study for this chapter is the text-centred memory practices of legal scholars of Ifrīqiya that led to the consolidation of the Mālikī community. The legal teachings of Mālik b. Anas (d. 179/795) were transmitted by his students to the scholars of the Islamic West shortly after his death, but the need to preserve the link with Mālik seem to have become more pressing in later periods.  These activities led to the rise and dominance of a religious orientation and a scholarly culture in the Islamic West, especially Qayrawān and Cordoba, that coalesced around the legal opinions of Mālik.  A unique collection of texts from the mosque library of Qayrawān that survive from this period shows that networks of textual transmission were crucial for sustaining the local juristic community.  Both our earliest Mālikī biographical dictionaries, and the majority of manuscript evidence testifying to an intensive scholarly activity in Qayrawān comes from the 4th/10th century when Ifrīqiya came to be ruled by the Fatimid dynasty, who openly challenged the juristic community of Qayrawān, yet hardly suppressed their teachings  in a way that is often assumed by modern scholars. Not only there is little evidence that the Fāṭimids persecuted scholars, but there is also more evidence to confirm that the Mālikī scholarly community of Ifrīqiya consolidated and thrived under the Fāṭimid rule.
As Mālikī legal works were compiled and commented upon by several generation of legal scholar in the Islamic West, members of the scholarly community also took care to commemorate their peers and forerunners in biographical collections. The earliest extant collection, Abū al-ʿArab al-Tamīmī’s (d. 332/944) Ṭabaqāt ʿulamāʾ Ifrīqiya is also from the 4ht/10th century. His ṭabaqāt was continued by his student al-Khushanī (d. 370/981?) titled Ṭabaqāt ʿulamāʾ Ifrīqiya wa-Tūnis, then by al-Mālikī’s (d. c. 967/1081) Riyāḍ al-nufūs, ʿIyāḍ’s (d. 544/1149) Tartīb al-madārik, Ibn Idhārī’s al-Bayān al-mughrib and al-Dabbāgh (d. 696/1295) and Ibn Nājī’s (d. 837/1433) Maʿālim al-īmān.  These works connected the scholars of the Islamic West to Mālik b. Anas and Medina, through stories such as the one about Saḥnūn’s compilation of the Mudawwana, and others who came before and after him. Within the framework of the ṭabaqāt and local history, these authors were also abe to connect the memory of these scholars to the history of their home region – Ifrīqiya, which reinforced the illusion of stability and continuity of the community, which is what spaces do for memory. 
On the other hand, the descendants of Muslim settlers from the east, like Abū al-ʿArab – a descendent of the garrison commander of Tunis who chose scholarly pursuits over a military career, wrote the history of Ifrīqiya into the grand narrative of Islam. The earliest memory of the Muslim community in the Maghrib thus revolves around the stories of the conquest, and reinforcing the Muslim frontiers (ribāṭa).  Abū al-ʿArab Ṭabaqāt begins with a section “on the virtues of Ifrīqiya", where the Prophet is quoted telling his companions: "You will mobilise armies and the best among them will be the army of the Maghrib."  The introductory chapter then continues with praising the Muslim settlers of Ifrīqiya who arrived in the Maghrib for jihād and ribāṭ, and a Prophetic hadith is cited through several narrators: “People of my community from Ifrīqiya will rise on the Day of Resurrection with their faces brighter than the full moon.”  These traditions praise and give credit to the virtuous Muslim settlers of Ifrīqiya, among them “the companions of the Prophet and those who came with the companions during their campaigns,” and the followers (tābiʿīn) who had personal limks to the East, are mentioned before the ʿulamāʾ and fuqahāʾ “generation after generation.”  The remembrance and commemoration of the earliest settlers, especially through reusing the powerful tropes of jihād and ribāṭ, and re-enacting and performing this memory remained important for many generations of scholars to come, including through participating in real combat. 
From the stories of their forefathers to personal memories of participation in military campaigns, jihād and ribāṭ were significant for the memory processes of the juristic community of 10th-11th century Ifrīqiya. The Fāṭimid rulers, who had replaced the Aghlabids following a dramatic takeover in 909 CE, but whose control over Ifrīqiya faded gradually towards mid 5th/11th century, came to be remembered as the antiheroes, especially after the Zīrid ruler turned against them. This political reality, as well as local and trans-local rivalries with other communities, thus inevitably played a part in the formation of communities and their sense of identity.
In the following century, this tension not only kept the memory of the latter’s direct rule in Ifrīqiya relevant but overtly political. The Fāṭimids had to be vilified, and their oppression remembered. As the hatred for the Fāṭimids grew, Mālikī biographers lionised local heroes. These include the hagiographies (manāqib) for al-Qābisī (403/1012) and Muḥriz b. Khalaf (d. 413/1022), who taught Abū Bakr al-Mālikī’s father. Another important influence on Abū Bakr al-Mālikī was his teacher ʿAbd al-Raḥmān al-Ajdābī  (d. 432/1040), who composed hagiographies of four militant ascetics who had joined the rebellion of Ibāḍī Berbers led by Abū Yazīd al-Nukkārī (d. 335/947) against the Fāṭimids.  Although Al-Ajdābī’s writings have not survived directly, it is his generation whose remembrance of the early Fāṭimid period with elements of anti-Fāṭimid propaganda, including fantastical details, made it into al-Mālikī biographical collection.
In addition to memories of struggle and perseverance, biographical collections make use of evocative narratives of suffering, namely trial (miḥna, pl. miḥan) and martyrdom. Already an established and culturally familiar theme across religions, utilised most effectively by the Shīʿis, biographers cast their members who clashed with the authorities as martyrs and oppressed. Abū al-ʿArab devoted an entire book to the subject which he titled The Book of Trials (Kitāb al-Miḥan), while al-Khushanī wrote an entire separate chapter in his Ṭabaqāt listing scholars who had been punished or executed by the rulers. The repetition of these stories arguably played a crucial role for consolidating and sustaining the scholarly communities such as the Mālikīs of Ifrīqiya:

You have asked me, may God protect you from the Devil and his actions, to compile a book mentioning the scholars, jurists, saints, ascetics and pioneers of Qayrawān and Ifrīqiya, including those along the coasts of Ifrīqiya and its ports and forts. I sought God’s guidance, took Him as my guide, and asked for His help, then recorded whatever information had reached me of their pious men and ascetics, their merits and praises, and their dates of death, to the extent of my capacity. I saw this as a way of commemorating them (iḥyāʾan li-dhikrihim) and spreading their merits to be remembered by those who commit [things] to memory, and as an example of guidance for those who seek a model and for the pious. 

This is how Abū Bakr al-Mālikī introduced his project to revive the memory of the pious men of Ifrīqiya in a compilation of written and oral material that he called Riyāḍ al-nufūs (Garden of Souls).  The fact that Abū Bakr al-Mālikī does not explicitly brand his work a specifically Mālikī work of ṭabaqāt but rather seems to adopt a larger perspective is noteworthy.  There is no doubt that Abū Bakr al-Mālikī was a staunch Mālikī; the reason for his omission of any explicit reference to Mālik or his madhhab may have been simply that Mālikī scholars in his time still identified largely with the school of Medina, rather than the person of Mālik b. Anas. The reuse of the Riyāḍ al-nufūs in Qāḍī ʿIyāḍ’s (d. 544/1149) emphatically Mālikī Tartīb al-madārik wa-taqrīb al-masālik li-maʿrifat aʿlām madhhab Mālik  (see Figure 1) reveals that the former must have been a model for Qāḍī ʿIyād, as well as one of his major sources on the Mālikīs of Ifrīqiya.

 
Figure 1. The reuse of biographical material from the Riyāḍ al-nufūs (top) in Tartīb al-madārik (bottom). The text of the books, divided into chunks of 300 tokens is laid along the x-axis, while y-axis shows the length of the aligned passages in each book. (The blank space in the beginning corresponds to editorial introductions.)


Qāḍī ʿIyāḍ’s Tartīb al-madārik quotes the Riyāḍ more than it does any other book. The data also shows that Qāḍī ʿIyāḍ reused all of the extant parts of the Riyāḍ in composing his Tartīb al- madārik. As a memory practice, biographical text reuse and the commentary tradition were essential for perpetuating Mālikīsm, and the distant reading approach proposed here may help our understanding of the Mālikisation of the Islamic West. In this regard, works of ṭabaqāt, transmission (riwāya), commentary (sharḥ) and abridgement (mukhtaṣar) complement each other in the consolidation of the juristic community.
Mālikī historians and biographers presented a history of the Islamic Maghrib that served to legitimise their community, connecting it to revered Arab pioneer settlers in the Maghrib and ultimately to the ṣaḥāba (the Prophet’s companions) and the Prophet. While integrating the Maghrib into the broader history of Islam, they appear to suppress the memory of other communities and disfavoured rulers. Elsewhere, the biographies combine the ideals of piety, asceticism, standing guard at the frontiers, avoiding and denouncing rulers, especially the Fāṭimids, in order to create convincing individual profiles and a collective portrait of the pious men of Ifrīqiya. 
That said, to assume that Mālikī historians and narrators were deliberately ideological in their remembrance of the past is perhaps too simplistic. Rather, there was a more complex process of meaning-making at work that predetermined their reception and recollection of the past and their arrangement and presentation of the available material. This process involved repetitive practices that enforced or promoted a particular identity, but also mundane activities that were hardly driven by ideology.  The biographical collections represent the first type – i.e. intentional memorialisation, while textual transmission is the less conspicuous form of memory practice, to which we return through the case of Saḥnūn b. Saʿīd  and textual practices centred on his Mudawwana, below. Before discussing the memory of Saḥnūn, it is worth further examining the narratives of struggle, suffering, and heroism, which we think are most relevant to communal identity formation for their poignancy, their capacity to evoke a sense of pride, and their putative status as most worthy of commemoration. 

Narratives of Struggle and Suffering

It is known that experiences of war and violence are often the focus of communal remembrance, both because of the trauma and suffering, and the haunting visual experience. But it is also known that one does not need to witness or experience these events personally. Moreover, insofar as these narrative plots are culturally familiar, they provide templates for telling new stories about more recent heroes. And because narratives of defiance, sacrifice and martyrdom play a key role in sustaining communities, they remain a productive theme in telling the story of the past to the point of being repetitive. The repetition of the patterns, as we observe in hagiographies and folk stories, is, however, hardly because of the lack of imagination on the part of the authors. Rather, as in the case of the stories of martyrdom or miḥna (ordeal, trial), the narrator aims to register the story as a repetition of the archetypal miḥna. The narrator is almost forced to change the story to fit the “culturally circulated stories,” in order for it to be meaningful.  As Kashima suggests, "the appropriation of culturally circulated stories" – in this case narratives centred around stories of piety, poverty, defiance, miḥna, jihād, ribāṭ and so on – would “result in the adoption of the stories’ goals."  Thus, the ṭabaqāt are not just a compilation of the pious deeds of exemplary scholars, but also a framework for telling the story of the community.  At the same time, as studies on the psychology of memory have shown, the existence of these cultural and social frameworks, or templates, has a direct influence on the formation of these recollections.  “False memory syndrome,” or adopting “common autobiographical stories about traumatic experiences and their negative consequence” is a known phenomenon in cognitive psychology.  One may go a little further and posit that in a similar way believable and culturally familiar tropes can also feed into cultural memory. For, as Straub observes,

[t]o visualize the past and history, one employs images and a language which is never completely one’s own. A person recollecting past events imagines and narrates them as a member of a certain culture […]. Without its symbolic forms and means one would search in vain for a specifically human memory. Without them, all those memories and narratives which help us vividly visualize and communicate the past and history of humankind, or even of one single individual, would disappear. 

These observations highlight the power of the ṭabaqāt over cultural memory, but these narratives are not restricted to the ṭabaqāt. Indeed, they are borrowed from the larger biographical tradition that was not unique to Arabs, Muslims, or only Sunni Muslims. In narratives that mirror the Biblical story of Moses, as well as Christian martyrology,  Ismāʿīlī, Ibāḍī and Mālikī authors of the Maghrib highlight the perseverance of their respective heroes in the face of oppression, using not only similar literary devices but often identical metaphors. In Ismāʿīlī polemical narratives, the non-Shīʿī jurists and scholars were accused of complicity in the legitimation of the unjust caliphs.  In a work written in the form of a didactic dialogue, the Kitāb al-ʿālim wa’l-ghulām, presumably during the revolutionary phase of the Fāṭimid daʿwa in the Yemen, Jaʿfar b. Manṣūr argued that the jurists were in fact worse than the usurpers of the caliphate, for: “Were it not for the opinions passed down and circulated by the legal scholars [riwāyāt al-fuqahāʾ], [...] the oppressors could not maintain their dominion over the foolish ones.”  The lengthy dialogue of course makes ample references to the “murder” and “suffering” of the Shīʿī imams at the hand of their oppressors. While Ismāʿīlī authors like Jaʿfar b. Manṣūr also maintained a cyclical understanding of time, framing the injustices (and their consequences) as an inevitable part of history, the narrative pattern of “righteous community ->> oppressor ->> martyrdom ->> relief/reward/victory” was shared by other communities.  Given how common this pattern was, it is hardly surprising that the Fāṭimid caliphs were themselves casted as impostors and tyrants by their Mālikī adversaries.

It is useful to consider the medieval Ismāʿīlī dāʿīs as a “control group” to highlight the wider cultural relevance of these narratives. While the Fāṭimid-Ismāʿīlī scholars did not produce a single ṭabaqāt work, they also relied on narratives of martyrdom and trials to legitimize their cause. A model of this genre is al-Qāḍī al-Nuʿmān’s Kitāb al-Manāqib waʾl-mathālib (Book of Virtues and Vices), in which he enumerates the vices of the Umayyads, an old rival of the Hāshimid clan and its ʿAlid branch that came head to head with the Fāṭimids (who were ʿAlids) one last time in the Maghrib.  For this major Fāṭimid author and his readers, the memory of the old battles in the Hijāz and ʿIrāq and the martyrs were therefore directly relevant to the political realities of the time, namely the confrontation with the Umayyads of al-Andalus. 
Finally, as Judith Pollmann has shown in the case of early modern Europe, while memory practices related to war and violence, such as the ones mentioned above, may begin much later in time, they also depend on others similar memories, and are shared by the victims only when it is possible to give them a positive meaning.  Pollmann also highlights the comforting role of religion in reframing memories of trauma, for which we have a perfect example from Qayrawān, Abū al-ʿArab al-Tamīmī’s introduction to his Kitāb al-miḥan, a long list of martyrdoms and ordeals beginning with the murder of the second caliph ʿUmar and ending with the persecution of scholars in his own time. According to this redemptive scheme, the suffering of Muslims, especially the pious among them is nothing but a blessing from God: indeed, the Prophet has said that “my people will suffer the most in this world”, and “the prophets and the righteous will suffer most”.  Another hadith that includes Saḥnūn in its isnad says: “every nation has a punishment and the punishment of my nation is the sword”.  In addition to the Prophet, there is a quote from the famous early Jewish convert to Islam, Kaʿb al-Aḥbār,  who was known as an expert of the sacred scriptures: “When you see swords unsheathed and blood spilled, know that God’s command had been forfeited; when you see the plague spread, know that adultery had spread; and when you see the rain was kept, know that the alms (zakāt) had been kept; when people withhold what is theirs  to give, God withholds what is his.”  The aim of these memory strategies, such as commemorating the martyrs, was also to create a solidarity community across the world, not too dissimilar from that described by Pollmann, with a shared memory of the losses, suffering, triumphs and defeats of the past. 
While equally polemical, narratives of triumph and defeat are not about self-pitying and victimhood. Instead, they are deployed in polemical texts to target rival communities, and cast representatives of the authors’ own communities as heroes.  Whereas in narratives of martyrdom and miḥna, defiant heroes suffer at the hands of tyrants, in narratives of polemics they demonstrate excellence and triumph. The most illustrative examples of these are found in the narratives of debates (munāẓara), which are usually presented as truthful accounts of polemical encounters.  The popularity of this genre among all religious communities and the abundance and circulation of texts attests to their role in creating competing communal memories.
On the contrary, humiliation and defeat present an inconvenience that must be justified by memory communities. For survivors, these experiences are traumatic and shameful, and cannot be used to promote a positive image of themselves or their community.  The memory of Abū Yazīd’s long-lasting but ultimately failed rebellion against the Fāṭimids is a telling example, which put both the Ibāḍīs and the Mālikīs who supported Abū Yazīd in an embarrassing situation, while it helped the Fāṭimids to secure their control over Ifrīqiya. Because of the importance of this victory for Fāṭimid propaganda, it was celebrated with parades,  commemorated in poetry and speeches, and implicit references were made to it in coinage and inscriptions.  Likewise, the victors made the most of Abū Yazīd’s corpse after he was killed, parading with it in all towns of Ifrīqiya before crucifying it in al-Mahdiya, after a ship which meant to take it to Sicily for a victory parade there sank off the coast of Ifrīqiya. When parading with the flayed corpse in the rebel town Tāhert, Fāṭimid imam-caliph al-Manṣūr billāh also ordered the dead bodies of former rebel governors of Tāhert Masāla b, Ḥabūs and his brother Yaṣal be exhumed and burned together with the pulpit of the mosque from where the name of the Umayyad caliph had been proclaimed.  It was not only an act of revenge and a message to the Andalusian caliph and the rebels he supported,  but also the erasure of all traces of defeat by the caliph who had adopted the regnal title al-Manṣūr bi-naṣr-Allāh that is ‘the Victorious with the Help of God’. At the same time, the defeated parties, the Ibāḍīs and the Mālikī jurists of Qayrawān had to come up with justifications for taking part in the rebellion, which, as Walker and Madelung have suggested, was one of the reasons for the portrayal of the Fāṭimids as heretical extremists in Mālikī historiography.  The damnatio memoriae of Abū Yazid also befell the Fāṭimids when their rule came to an end: their names was erased even from their own tombstones.
As these examples amply demonstrate, social memory is anachronistic and fluid. Remembrance and commemoration of individuals, events, and the narrative format of these memories were crucial for imagining the past and having a sense of a communal identity. Traumatic memories, wars, violence, and heroic acts readily fit culturally familiar frameworks for storytelling. While the framing of the past stories was determined by the present, they were also oriented towards the future, aimed at motivating the actors to behave in accordance with the imagined tradition, propagating allegiance to one madhhab over others. That these allegiances and networks were only occasionally harnessed by temporal political powers, less so conflated with state identity (there are exceptions) probably ensured the durability of these communities in a way that a tribal identity, for example, could not. (KENNEDY) Therein lies the power of a minority, but highly connected scholarly class and its control over the memory of the Muslim community. (These imagined communities were purportedly independent of states and bound together different ethnic groups across the Muslim world). The following pages will focus on one and arguable the most illustrious jurist of medieval Qayrawān to illustrate how a community of jurists functioned across several generations.

Par 2: The Memory of Saḥnūn and Textual Networks in Qayrawān
Saḥnūn b. Saʿīd was an influential transmitter of the legal opinions of the scholars of Medina (and Egypt), students of Mālik b. Anas, to a large number of students of Ifrīqiya and al-Andalus.  Being the most senior among those who never met or directly studied with Mālik, his laborious endeavour to compile the legal knowledge from all direct students of Mālik paid off. The number of his disciples is reported to have reached seven hundred, attracting both scholars and ascetics from all corners of the world.  He is credited for the triumph of Mālikism in Ifrīqiya through the dissemination of his legal compendia, the Mudawwana, which, as mentioned in the story of its composition, compiled and consolidated a great deal of Mālik’s teaching.  The transmission of these works, accompanied by an emerging textual tradition, went back to Saḥnūn through his closest associates and numerous disciples, including his son, also a prolific scholar, Muḥammad b. Saḥnūn (d. 256/870). While most scholars have sought to reconstruct Saḥnūn’s legal works, biography, number of disciples, and so on, based on textual and material evidence, it is likely that the portrait of Saḥnūn is likely a later construction, even if the Mudawwana was largely the product of his own efforts.  Biographical dictionaries do record Saḥnūn’s high esteem among his contemporaries, but it is also clear that the full measure of his contribution was only appreciated/realised in the tenth century.

 
Figure 2. While Saḥnūn’s Mudawwana builds on the opinions of Mālik b. Anas it also includes much material that is not found in the Muwaṭṭa, including opinions of other Mālikī jurists, aḥādīth and āthār: (top Muwatta, bottom Mudawwana). Some scholars (notably Norman Calder, Nicolle Cottart) believed that the text of the Mudawwana was not fixed during Saḥnūn’s lifetime.
Modern scholarship has followed the classical Mālikī consensus about the pre-eminent role of Saḥnūn’s oeuvre in consolidating Mālikism in Ifrīqiya and al-Andalus.  Material evidence – manuscript fragments from Raqqāda collection confirm Saḥnūn’s Mudawwana as the most widely transmitted text. Although their dating to the 3rd/10th century is problematic, some of the oldest (non-Qurʾanic) textual fragments preserved in the collection of the Great Mosque of Qayrawān are from the Mudawwana, one of them believed to have been written during Saḥnūn’s lifetime (a single folio written before 235 AH).  It needs to be  explained, therefore, why and how this compilation, often presented as a transmission of Mālik’s legal opinions through his Egyptian student Ibn al-Qāsim (d. 191/807), should have surpassed the efforts of all other legal schools and jurists in North Africa and al-Andalus. What is more, as mentioned in the beginning of this chapter, the original compilation, on which Mudawwana was supposedly based, according to the Mālikīs’ own belief, was actually compiled by Asad b. al-Furāt following a Ḥanafī framework.  The answer is often sought either in the text of the Mudawwana (what made it so outstanding?), or in the Aghlabid patronage, which made Qayrawān such a thriving environment for legal studies?), without considering the social and political context in which Saḥnūn’s legacy and memory was circulating.  Therefore, the focus is on the early Fāṭimid period (4th/10th century), in which the majority of our biographical texts and much of the extent manuscript evidence was produced and the Mālikī school was consolidated.
The earliest biographies of Saḥnūn present a more modest portrait of him than the later, even including reservations by some of his own students, including reservations abou the merit of his Mudawwana.  At the same time, many other works by Mālikī authorities were in circulation, including the above-mentioned Asadiyya.  Thus, the image of Saḥnūn, created by later generations as a prodigious and exemplary champion of the Mālikī school, I suggest, was less due to his activity as a jurist, or as a champion of the public against the Aghlabids, than to the consolidation of the Mālikī madhhab/memory – community, which crystallised during the Fāṭimid period, and was in need of local heroes. Transmission of Mālikī legal knowledge compiled in the Mudawwana (Figure 3), played a crucial role in this process, and can be demonstrated through the intensity of the transmission of his works attested in the ṭabaqāt and surviving manuscripts (Figures 4).
 
Figure 3. Major authorities quoted in the Mudawwana. The graph represents the occurrences of explicit citation from top six Mālikī authorities per milestone (300 tokens, roughly one printed page) across the text of the Mudawwana, which has almost 1 million words/tokens divided into 3000 milestones. As a search term, I used “qāla”+ “narrator.” For comparison, there are 107 hadith quoted using the formulation “qāla rasūl Allah.”

 
Figure 4. An overview of the textual network formed through participation in transmitting the same texts. The red links represent authoring (taʾlīf, taṣnīf, etc.), and green links represent transmission (riwāya) of a book (orange nodes) by an author – represented by a colour according to one of the four periods. This network is based on information from biographical dictionaries, in many cases attested in transmission notes on manuscripts compiled by Miklos Muranyi in his Beiträge. Please refer to the interactive version of the network, which allows filtering by clusters and by period: https://aslishah.github.io/Qayrawan/ 
As the visualisation of the textual network shows, while Saḥnūn was not a prolific author in a sense that he has not left us any other book, his massive compilation the Mudawwana was one of the most transmitted works among the Mālikī community, effectively a school textbook. The network also confirms that Saḥnūn’s authority was not undisputed. The isolation of the venerated scholar and major source for Mālikī biographers, Saʿīd b. al-Ḥaddād, who apparently did not take part in the transmission of legal works by his predecessors, including his teacher Saḥnūn, is a case in point. The study of his personal networks in the Mālikī ṭabaqāt confirms the reports that he was somewhat ostracised by the Mālikī community. Yet, he was posthumously rehabilitated and accorded a prominent position in the Mālikī biographical dictionary, particularly because of his disputations with the Fāṭimid dāʿīs.  Saḥnūn himself does not appear as prominent as one might expect, because he did not produce many titles, however, his Mudawwana is central to the network and most of the other scholars participate in its transmission. An interactive version of this graphic is currently available online: https://aslishah.github.io/Qayrawan/ which will be improved and made available with this publication.
The surviving catalogue of the manuscript collection of the Great Mosque of Qayrawān, and the collection itself demonstrates the growing significance of the Mudawwana in the Fāṭimid and Zīrid period. There is no doubt that the Mālikī jurists used Saḥnūn’s works in their day-to-day activities, an obvious reason for its intense transmission.  As manuscript and text reuse data show (Figure 7), by the Zīrid period the Mudawwana became the most transmitted work in Qayrawān. At the same time, the biographies of Saḥnūn expanded and separate accounts of his virtues were composed, as noted above.
The scholars of Qayrawān many of whom were Saḥnūn’s students, remembered him as a staunch defender of the school of Medina (Mālikīs) in the context of bitter revenge and humiliation from the ʿIrāqīs (Ḥanafīs) in the late Aghlabid period (late third/ninth century). Only a handful of the students and contemporaries of Saḥnūn, who had memories of him, lived into the early Fāṭimid period and transmitted eyewitness accounts alongside his emerging hagiography to a new generation of Mālikīs, who, almost sixty years after his death, began to compile the accounts of his virtues (manāqib).  The Fāṭimid reality, especially the state’s pressure on the jurists is thus key to understanding the formation of the Mālikī memory, which excluded not only rival communities (Shīʿīs, Ibāḍīs, Ḥanafīs), but also plurality and disagreement within the community. For instance, the Ifrīqiyans who followed al-Shāfiʿī were later reclaimed by the Mālikīs. Abū Bakr al-Mālikī’s father, who was known as “al-Shāfiʿī,” was ostensibly encouraged by his teacher al-Qābisī to change his nisba to “al-Mālikī,” which points to the major preoccupation of the authors of the ṭabaqāt.
	The activities of the juristic community of Qayrawān centred around the transmission of the Mudawwana amounted to a canonisation of a sort. According to Aleida Assmann, canonisation involves a) the maintenance of texts, as I have reconstructed in Figure 4; b)  the maintenance of meaning, which is signalled by the emergence of commentaries and abridgements, as captured by text reuse evidence (Figure 6, 7; Appendix 1); and c) censorship, of which the censorship of Asad b. al-Furāt and his contribution is one example.  Textual evidence also allows us to reconstruct the transition from the communicative, almost autobiographical narration of the Mudawwana, and its function as a school  text (as shown by Miklos  Muranyi and Jonathan Brockopp), to cultural memory in its final shape, spanning 80-100 years, as described by Jan Assmann.  The appearance  of the massive Kitāb al-Nawādir waʾl-ziyādāt by Ibn Abī Zayd al-Qayrawānī, dealing with cases not included Saḥnūn’s compilations, as well as his “book  by  book and chapter by chapter” abridgement entitled Ikhtiṣār al-Mudawwana waʾl-Mukhtaliṭa, not only confirms  the “closure” or the consolidation of the text, but also its canonicity.  For sceptics, the early 5th/11th century abridgement by al-Barādhiʿī (Fig 4), and the Jāmiʿ li masāʾil al-Mudawanna (Appendix 1) by the contemporary Ibn Yūnus al-Siqillī, should leave no room for doubt that by this time the Mudawwana had already achieved its status as the most authoritative compendium of the Mālikī school in Qayrawān and Ifrīqiyya.
	
 
Figure 5. Top: Tahdhīb al-Mudawwana, an important abridgement of Saḥnūn’s Mudawwana, by Abū Saʿīd al-Barādhiʿī al-Qayrawānī (d. 438/1046-47); bottom: Mudawwana, after Ibn Abī Zayd’s (d. 386/996) Ikhtiṣār, with which the tradition of making abridgements of Saḥnūn’s Mudawwana begins. These abridgements and multiple early commentaries testify to the popularity of the book and had practical significance for teaching..
These activities went hand in hand with the growing importance of Saḥnūn in the community’s remembrance of its past, which can be captured by Pierre Nora’s concept lieux de mémoire or “the sites of memory.” The remembrance of Saḥnūn by later generations who were mostly removed from Saḥnūn’s Qayrawān in time or space, like tenth century Abū al-ʿArab and al-Khushanī, and Abū Bakr al-Mālikī who wrote a century later after the total destruction of Qayrawān, like Abū Bakr al-Mālikī, were inevitably shaped by their own environments.  Subsequently, as Brockopp notes, contradictory stories about Saḥnūn  are reported as historical facts in modern scholarship.  In reappraising the biographical tradition, my aim is not to downplay the crucial role of the historical Saḥnūn and his teaching, but rather to interpret the role of the hagiographic accounts elaborated by Mālikī scholars from the Fāṭimid period onwards in the formation of the tradition. This is also the context for a process in which the mudawwana (compilation) of Asad b. al-Furāt, became the Mudawwana of Saḥnūn b. Saʿīd and transmitted on his authority among the expanding Mālikī network (see Figure 7).



 
Figure 6. Saḥnūn’s network of students and teachers. The network of Saḥnūn and his Mālikī teachers and students based on the Ṭabaqāt al-ʿulamāʾ by Abū al-ʿArab al-Tamīmī (d. 333/945). Students associated with a teacher are identified and coloured by a clustering algorithm.
 Alongside the transmission of the Mudawwana, the collective remembrance of Saḥnūn by his students and their students, a group often connected through more than textual networks, passed on between generations of Mālikīs.  Since this “remembrance” or “reconstruction of the past” was inevitably embedded in their present, as Halbwachs had postulated,  it must also reflect the memory processes that shaped the Mālikī community, especially the most important religious and political change in Ifrīqiya since the time of Saḥnūn – the Shīʿī Fāṭimids’ takeover of the Aghlabid state in 909, who then challenged the fuqāhāʾ’s authority as “heirs to the Prophet.” The implication of the political context for the Mālikī community of Qayrawān therefore needs closer consideration.
If inter-madhhab competition and the need for consolidation led to the construction of a heroic image for Saḥnūn in the memory of his tenth-century colleagues, for a similar reason his stature came to be eclipsed by  that of his teacher Ibn al-Qāsim, who was elevated above Saḥnūn in the process of the codification or creating a uniform theory for Mālikī law in the post-classical period.  Up until the 7th/13th century, text reuse evidence demonstrates the continuous importance of the Mudawwana for the Mālikīs in Ifriqiyya. (See, Figure 7: systematic commentary on the Mudawwana). However, the need for a uniform doctrine led to the rise of the new forms of mukhtaṣar, which for the Mālikīs seems to have started with Ibn Shās’s ʿIqd al-Jawāhir al-Thamīna, then Ibn al-Ḥājib’s (d. 646/1248) Jāmiʿ al-ummahāt, and culminated in the famous Mukhtaṣar Khalīl of Khalīl b. Isḥāq al-Jundī (d 749/1348 or 767/1365).  The popularity of Ibn al-Ḥājib’s mukhtaṣar among the Mālikīs in both Egypt and in the Maghrib, alongside the above-mentioned Tahdhīb al-Mudawwana, was already observed by his later contemporary Ibn Khaldūn.   These highly technical, and complex works seem to have gradually rendered the classical textbooks, such as the Mudawwana, obsolete.  

 
Figure 7. Text reuse pattern in Saḥnūn’s Mudawwana shows that the three top reusers are abridgements of the work. These systematically quote 100-word chunks from the Mudawwana. See, the graphical representation of the top two reuser Ibn Yūnus’s Jāmiʿ in Appendix 1, and Abū Saʿīd al-Qayrawānī’s Tahdhīb in Figure 5 above. There are also other works which do not quote the text systematically, but they are important indicators of the canonicity of the Mudawwana, such as al-Jubbī’s (d.450/1058) Kitāb sharḥ gharīb alfāẓ al-Mudawwana, which again indicates that the commentator assumed the work to have been a closed corpus.
	In the long run, as Ahmed El Shamsy has argued, the proliferation of the commentary tradition, seem to have obscured the classics only to be revived in the modern age. By the beginning of the twentieth century no complete copy of the Mudawwana could be found in either Egypt or Tunisia, which led Muḥammad Abduh (d. 1905) to fetch a copy from Morocco for the first Egyptian edition of 1905-05.  Unlike the classical unambiguous acknowledgement of Saḥnūn as the compiler of the Mudawwana, modern editions tend to attribute the Mudawwana to Mālik b. Anas highlighting Ibn al-Qāsim’s role as its transmitter, echoing the post-classical shift from Saḥnūn to Ibn al-Qāsim and Mālik b. Anas.  Ironically, when the edition appeared in July 1905, Abduh’s own contribution was left unacknowledged: there was no mention of him in the colophon, making him the last casualty of traditionalism. 

Part 2. Narrative Frameworks of Memory: Ṭabaqāt as Memory Texts
Much of what has been discussed above, including the personality of the scholars, their standing within the community, social relations, and credentials is preserved and transmitted in the biographical dictionaries of the Mālikī school, also called ṭabaqāt and tarājim. The biographical dictionaries are first and foremost commemorative communal texts, which serve to define the community. Scholars have long debated about the function of Muslim biographical collections, categorising them variously from encyclopaedia and reference tools to communal histories.  However, most of them seem to agree on at least one important characteristic of the genre: that it presented an argument for a community, and its legitimacy in the case of a scholarly community. The ṭabaqāt connected the scholars of a madhhab in successive generations back to the Prophet. Modern scholars still seem to give priority to this function of the ṭabaqāt as the main motivation behind these repetitive compositions. The focus here is, however, on the role of the ṭabaqāt as a product of memory communities, and on the significance of the “horizontal” mode of knowledge transmission  and the rise of the ṭabaqāt. This approach contrasts with that of the Ismāʿīlīs, who, unlike many other Muslim communities, did not compose works of ṭabaqāt.
	The contrast with the Ismāʿīlīs among others, is significant. As Shahzad Bashir has recently argued, the ṭabaqāt create a sense of community across generation, even within a generation, between people who had no interaction. This allows us to observe “how variation between biographical genres [and perhaps other genre] leads to radically different temporalities pertaining to a single socio-political context.” 
	
As a traditionalist group, the Mālikīs sustained a continuous interest in compiling ṭabaqāt beginning with the late third/eighth and early fourth/ninth centuries.  The function of the ṭabaqāt was, Makdisi maintained, “to distinguish between those who had the necessary knowledge to be qualified as authoritative, and those who did not,” aimed at empowering “a certain group of scholars to the exclusion of others.”  Limiting the utility of the ṭabaqāt for a particular group - the traditionalists, Makdisi also downplayed the interest of other groups in compiling biographical dictionaries, including kalām theologians, poets, Qurʾān reciters, and others. Conversely, Tarif Khalidi discounted the primacy of ḥadīth and concerns of authenticity and authority and included a wider range of “literary interests,” such as pre-Islamic “genealogy and chain of poetic transmission,” early Islamic “short biographies” of the companions of the Prophet, the ʿulamāʾ and other prominent people, and only lastly the “lists of [ḥadīth] transmitters” as the precursors to biographical dictionaries.  More recently, Michael Chamberlain and Wadad al-Qadi linked biographical collections to the self-consciousness of the ʿulamāʾ as a class, and to social struggle and survival.  In a survey of the two earliest extant Mālikī biographical dictionary of the scholars of Ifrīqiya, Maribel Fierro also shows the significance of books, their writing, ownership and circulation as a form of social capital in the third-fourth/ninth-tenth century Maghrib, as reflected in the ṭabaqāt.  In another study, Maribel Fierro views the ṭabaqāt as a repository of memory, practice, and networks of religious scholars.  Michael Cooperson, emphasised the function of biography in bolstering the claims of various social groups to “heirship of the prophet,” among them the ʿulamāʾ, and drew attention to “the power of biography in creating and sustaining of communities of faith.”  Claims to the heirship of the Prophet seems to have been an important function of the biographical collections. This also must have been the reason why the Ismāʿīlī scholars and dāʿīs, who considered only the Ismāʿīlī imams as the rightful heirs of the Prophet, did not compose biographical dictionaries.  




 
APPENDICES

Appendix 1. Top reuser of the of the Mudawwana in the Open Islamicate Initiative Corpus

 Top, Mudawwana, bottom, Ibn Yūnus al-Ṣiqillī’s (d. 454/1059) Jāmiʿ li masāʾil al-Mudawwana, which is closely followed by Abū Saʿīd al-Barādhiʿī al-Qayrawānī’s (d. 438/1046-47) Tahdhīb al-Mudawwana, in Figure 5, above.

 


BIBLIOGRAPHY

Abū al-ʻArab, Kitāb al-Miḥan, Yaḥyā Wahīb al-Jabbūrī (ed.), 3rd edition (Beirut: Dār al-Gharb al-Islāmī, 2006).
Abū al-ʿArab, and al-Khushanī, Kitāb Ṭabaqāt ʿUlamāʾ Ifrīqiya=Classes Des Savants de l’Ifrīqīya (Paris: E. Leroux, 1915), vol. 51–51.
Assmann, Aleida, ‘Canon and Archive’, in Astrid Erll and Ansgar Nünning (eds), Cultural Memory Studies: An International and Interdisciplinary Handbook (Berlin & New York: De Gruyter, 2008), 97–108.
Assmann, Jan, ‘Communicative and Cultural Memory’, Cultural Memory Studies: An International and Interdisciplinary Handbook (Berlin & New York: De Gruyter, 2008), 109–18.
Azouvi, François, ‘Descartes’, in Pierre Nora and Lawrence D Kritzman (eds), Arthur Goldhammer (tran), Realms of Memory: The Construction of the French Past, Vol. 3, Symbols, 3 vols (New York; Chichester: Columbia University Press, 1998).
Bennison, Amira K., The Almoravid and Almohad Empires (Edinburgh: Edinburgh University Press, 2016).
Brockopp, Jonathan E., ‘Contradictory Evidence and the Exemplary Scholar: The Lives of Sahnun b. Saʿid (d. 854)’, International Journal of Middle East Studies, 43/1 (2011), 115–32.
———, ‘Literary Genealogies from the Mosque-Library of Kairouan’, Islamic Law and Society, 6/3 (1999), 393–402.
———, Muhammad’s Heirs: The Rise of Muslim Scholarly Communities, 622–950 (Cambridge: Cambridge University Press, 2017).
———, ‘Saḥnūn b. Saʿīd (d. 240/854)’, in Oussama Arabi, David S Powers, and Susan A Spectorsky (eds), Islamic Legal Thought: A Compendium of Muslim Jurists (Leiden: Brill, 2013).
———, ‘Saḥnūn’s Mudawwanah and the Piety of the “Sharīʿah-Minded”’, in A Kevin Reinhart and Robert Gleave (eds), Islamic Law in Theory: Studies on Jurisprudence in Honor of Bernard Weiss (Brill, 2014), 129–41.
Cubitt, Geoffrey, History and Memory, Historical Approaches (Manchester: Manchester University Press, 2007).
Custers, Martin H., Al-Ibadiyya. A Bibliography: Second, Revised and Enlarged Edition., 3 vols (Georg Olms Verlag, 2017).
al-Dabbāgh, ʻAbd al-Raḥmān b. Muḥammad, and Abū’l-Qāsim b. Īsā Ibn Nājī, Maʻālim al-īmān fī maʻrifat ahl al- Qayrawān, Ibrāhīm Shabbūḥ (ed.), 4 vols (Cairo: Maktabat al-Khānjī, 1968).
al-Darjīnī, Aḥmad ibn Saʻīd, Kitāb Ṭabaqāt al-mashāʼikh bi-al-Maghrib (Qusanṭīna: Maṭbaʻat al-Baʻth, 1974), ShamIbadiyya version, ii, 115/OpenITI.
El Shamsy, Ahmed, Rediscovering the Islamic Classics: How Editors and Print Culture Transformed an Intellectual Tradition (Princeton, NJ: Princeton University Press, 2020).
Fadel, Mohammad H., ‘The Social Logic of Taqlīd and the Rise of the Mukhataṣar’, Islamic Law and Society, 3/2 (1996), 193–233.
Fentress, James, and Chris Wickham, Social Memory (Oxford: Blackwell, 1992).
Francesca, Ersilia, ‘Abū Ghānim Bishr b. Ghānim al-Khurāsānī’, Encyclopaedia of Islam, 3rd Ed.
Geary, Patrick J, Phantoms of Remembrance: Memory and Oblivion at the End of the First Millennium (Princeton: Princeton University Press, 1996).
Ghersetti, Antonella, ‘Classes of Grammarians East and West: Ṭabaqāt al-Naḥwiyyīn Wa-l-Lughawiyyīn of al-Zubaydī and Marātib al-Naḥwiyyīn of Abū l-Ṭayyib al-Lughawī’, Journal of Abbasid Studies, 7/2 (2020), 145–81.
Granara, William, ‘Ibn Sabīl: Crossing Boundaries in the Biography of Asad Ibn al-Furāt’, Scripta Mediterranea, 20 (1999), 259–67.
Halbwachs, Maurice, The Collective Memory, Francis J. Ditter Jr. and Vida Yazdi Ditter (trans.) (New York,  Cambridge, London: Harper & Row, 1980).
Halm, Heinz, The Empire of the Mahdi: The Rise of the Fatimids, Michael Bonner (tran.) (Leiden; New York: E.J. Brill, 1996).
Hentati, Najmeddine, ‘Min Al-Asadiyya Ilā al-Mukhtaliṭa f’al-Mudawwana’, in Najmeddine Hentati (ed), Murāsilāt Ḥaḍāriyya Ḥawla Al-Qayrawān (Tunis: Markaz al-Dirāsāt al-Islāmiyya, 2015).
Hoffman, Valerie J., The Essentials of Ibāḍī Islam (Syracuse, N.Y: Syracuse University Press, 2012).
Ibn Abī Zayd al-Qayrawānī and Aḥmad ʿAbd al-Karīm Najīb, Ikhtiṣār Al-Mudawwana Waʾl-Mukhtaliṭa (al-Qāhira: Markaz Najībawayh li-l-Makhṭūtāt wa Khidmat al-Turāth, 1434).
Ibn Khaldūn, ʿAbd al-Raḥmān, The Muqaddimah: An Introduction to History, Franz Rosenthal (tran.), 2nd Edition, 3 vols (Princeton, NJ: Princeton University Press, 1967).
Lewicki, Tadeusz, ‘Abū G̲hānim Bis̲h̲r b. G̲h̲ānim al-K̲h̲urāsānī’, Encyclopaedia of Islam, 2nd Ed. (Brill, 2012).
———, ‘Al-Ibāḍiyya’, Encyclopaedia of Islam, 2nd Ed. (Brill, 2012).
Love, Paul M., Ibadi Muslims of North Africa: Manuscripts, Mobilization, and the Making of a Written Tradition (New York: Cambridge University Press, 2018).
Madelung, Wilferd, and Paul E. Walker, eds., Affirming the Imamate: Early Fatimid Teachings in the Islamic West: An Arabic Critical Edition and English Translation of Works Attributed to Abū ʿAbd Allāh al-Shīʿī and His Brother Abu’l-ʿAbbās, Bilingual edition (London and New York: I.B. Tauris, 2021).
al-Mālikī, Abū Bakr, Kitāb Riyāḍ ʾal-nufūs fī ṭabaqāt ʻulamāʾ al-Qayrawān wa Ifrīqiya, Bashīr Bakkūsh (ed.) (Beirut: Dār al-Gharb al-Islāmī, 1981).
Marin, Manuela, ‘Ifriqiya et Al-Andalus, à propos de la transmission des sciences islamiques aux premiers siècles de l’Islam.’, Revue des mondes musulmans et de la Méditerranée, 40/1 (1985), 45–53.
Melchert, Christopher, The Formation of the Sunni Schools of Law, 9th-10th Centuries C.E. (Leiden: Brill, 1997).
Muranyi, Miklos, Beiträge zur Geschichte der Ḥadīt̲- und Rechtsgelehrsamkeit der Mālikiyya in Nordafrika bis zum 5. Jh. d.H.: bio-bibliographische Notizen aus der Moscheebibliothek von Qairawān (Otto Harrassowitz Verlag, 1997).
———, Die Rechtsbücher Des Qairawāners Sahnūn b. Saʿīd: Entstehungsgeschichte Und Werküberlieferung (Stuttgart: Franz Steiner, 1999).
———, The First Compendium of Ibadi Law: The Mudawwana by Abu Ghanim, Bishr b. Ghanim al-Khurasani. (Hildesheim Zürich New York: Georg Olms Verlag AG, 2018).
Nigst, Lorenz, Maxim Romanov, Sarah Bowen Savant, Masoumeh Seydi, and Peter Verkinderen, ‘OpenITI: A Machine-Readable Corpus of Islamicate Texts [Data Set]’ (Zenodo, 2021), https://zenodo.org/record/5550338 [accessed 14 March 2022].
Opwis, Felicitas, ‘The Role of the Biographer in Constructing Identity and Doctrine: Al-ʿAbbādī and His “Kitāb Ṭabaqāt al-Fuqahāʾ al-Shāfiʿiyya”’, Journal of Arabic and Islamic Studies, 11 (2011), 1–35.
Pollmann, Judith, Memory in Early Modern Europe, 1500-1800 (Oxford: Oxford University Press, 2017).
Qāḍī ʿIyad, Tartīb al-madārik wa-taqrīb al-masālik li- ma`rifat aʿlām madhhab Mālik, Aḥmad Bakīr Maḥmūd (ed.) (Beirut: Maktabat al-Ḥayāt, 1968).
Qurboniev, Aslisho, ‘The Writing of Munāẓarāt in Times of Turmoil: Disputations in Fatimid Ifrīqiya’, The Medieval Globe, 5/2 (2019), 59–86.
Schmitz, M., ‘Kaʿb Al-Aḥbār’, Encyclopaedia of Islam, 2nd Ed., 2012.
Stanković, Isidora, ‘Spaces of Memory – “The Presence of Absence”, Cultural Memory and Oblivion Mechanisms’, Култура/Culture, 8 (2014), 87–94.
Szpociński, Andrzej, ‘Sites and Non-Sites of Memory’, Teksty Drugie: Memory and Place, 1/Special Issue, English edition (2016), 245–54.
Talbi, Mohammad, ‘Rustamids’, Encyclopaedia of Islam, 2nd Ed. (Brill, 2012).
———, ‘Saḥnūn’, Encyclopaedia of Islam, 2nd Ed. (Brill, 2022).
al-Warjalānī, Abū Zakariyāʼ, Kitāb siyar al-aʼimma wa-akhbārihim al-maʻrūf bi-Taʼrīkh Abī Zakariyāʼ, 2nd edition (Beirut: Dār al-Gharb al-Islāmī, 1982).
al-Warjalānī, Abū Zakariyāʾ, Chronique d’Abou Zakaria: Publiée pour la premiére fois, Émile Masqueray (tran.) (Algiers: Imprimerie de l’Association ouvière V. Aillaud et cie, 1878).
ʿIyāḍ ibn Mūsā, Tartīb al-madārik wa-taqrīb al-masālik li-maʿrifat aʿlām madhab Mālik, Saʻīd Aḥmad Aʿrāb (ed.) (al-Rabāṭ: Wizārat al-Awqāf wa-al-Shuʼūn al-Islāmīyah, 1981).


